title: dhbw-mannheim-test
tagline: A brand new course on Learning Lab
description: dhbw-mannheim-test
template:
  repo: dhbw-mannheim-test-template
  name: dhbw-mannheim-test
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
